#! /bin/sh

set -e

if [ -z "$1" ]; then
    echo "usage: $0 <listname> [src...]"
    exit 1
fi

list_name=$1
shift 1

list_modules()
{
    for src in $@; do
        list=`sed -rn -e 's/^\s*MODULE_LUA_(BINDING|REGISTER)\((.*)\)\s*$/\2/p' "$src"`
        for mod in $list; do
            echo $mod
        done
    done
}

list=`list_modules $@ | sort`

echo '/* initializer prototypes */'
for mod in $list; do
    echo "MODULE_LUA_BINDING($mod);"
done
echo

echo '/* list of pointers to init functions */'
echo -n "#define $list_name"
for mod in $list; do
    echo ' \'
    echo -n "    luaopen_${mod},"
done
echo
